### ISSUE TITLE
Support the Altair json data transformer

### ISSUE THREAD

**Issue by joelostblom** [vegawidget/vegawidget#158]
I have run into an issue when trying to use Python's Altair via reticulate for a dataset with over 5000 rows. This works for smaller data sets thanks to vegawidget via using `as_vegaspec` or `vw_to_svg` as in this example:

````
---
title: "Altair-reticulate"
output: html_document
---

```{r load_packages}
library(vegawidget)
library(reticulate)
```

```{python}
import altair as alt
import pandas as pd

source = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]})
chart1 = alt.Chart(source).mark_bar().encode(
    alt.X('a:N',title='X-Axis label'),
    alt.Y('b:Q',title='Y-axis label')).to_json()
chart1
```

```{r}
vw_to_svg(py$chart1)
```
````

However, if I add the `alt.data_transformers.enable('json')` after the import statements, I get the following error message: 

```
Error in vw_to_svg("{\n \"$schema\": \"https://vega.github.io/schema/vega-lite/v4.8.1.json\",\n \"config\": {\n \"view\": {\n \"continuousHeight\": 300,\n \"continuousWidth\": 400\n }\n },\n \"data\": {\n \"format\": {\n \"type\": \"json\"\n },\n \"url\": \"altair-data-75a0d936e567cb7919580ae9c42873da.json\"\n },\n \"encoding\": {\n \"x\": {\n \"field\": \"a\",\n \"title\": \"X-Axis label\",\n \"type\": \"nominal\"\n },\n \"y\": {\n \"field\": \"b\",\n \"title\": \"Y-axis label\",\n \"type\": \"quantitative\"\n }\n },\n \"mark\": \"bar\"\n}") : Error in compiling to svg: WARN Loading failed altair-data-75a0d936e567cb7919580ae9c42873da.json TypeError: Only absolute URLs are supported at getNodeRequestOptions (/home/joel/R/x86_64-pc-linux-gnu-library/4.0/vegawidget/bin/node_modules/node-fetch/lib/index.js:1293:9) at /home/joel/R/x86_64-pc-linux-gnu-library/4.0/vegawidget/bin/node_modules/node-fetch/lib/index.js:1393:19 at new Promise (<anonymous>) at fetch (/home/joel/R/x86_64-pc-linux-gnu-library/4.0/vegawidget/bin/node_modules/node-fetch/lib/index.js:1390:9) at Object.http (/home/joel/R/x86_64-pc-linux-gnu-library/4.0/vegawidget/htmlwidgets/lib/vega/vega.min.js:1:9356) at Object.Nt [as load] (/home/joel/R/x86_64-pc-linux-gnu-library/4.0/vegawidget/htmlwidgets/lib/vega/vega.min.js:1:8422) at async HB.request (/home/joel/R/x86_64-pc-linux-gnu-library/4.0/vegawidget/htmlwidgets/lib/vega/vega.min.js:1:57897) at async HB.preload (/home/joel/R/x86_64-pc-linux-gnu-library/4.0/vegawidget/html
```

Sorry for the terrible formatting, this is how it shows up in RStudio. The main error message is: `Error in compiling to svg: WARN Loading failed altair-data-75a0d936e567cb7919580ae9c42873da.json TypeError: Only absolute URLs are supported at getNodeRequestOptions`

I tried changing the path to the absolute version by prefixing `file://` (at least I think that is the absolute syntax), but then I run into this error instead:

```
Error in compiling to svg: WARN Loading failed file://altair-data-75a0d936e567cb7919580ae9c42873da.json Error: No file system access. at i 
```

Do you have any idea if I could do something on my end to work around this issue, or it is simply not supported by vegawidget? Unfortunately I think I have to use the json transformer because the data-server transformer freezes reticulate (i believe it doesn't support nested python calls) and just disabling the max row warning takes several minutes to create a single plot in reticulate.

**Comment by ijlyttle** [comment]
Hi @joelostblom,

In the most-recent version of vegawidget, there's a function `vw_set_base_url()` that might be handy. It is written up in the most-recent Altair: <https://vegawidget.github.io/altair/articles/field-guide-rendering.html#rendering-speed-for-interactive-work>

Does this help this situation?

**Comment by joelostblom** [comment]
I should also say that I am using `vegawidget 0.3.2` and `altair 4.1.0` (Python).
